server.port=8082
spring.application.name=authentication-service

# ? CORREGIR: Usar el nombre del servicio Docker
gateway.url=http://gateway:8081/api

# JWT Configuration
jwt.secret=mySuperSecretKeyForJWTGenerationInProductionChangeThisInProduction123456789012345678901234567890
jwt.expiration=3600000
jwt.refresh-expiration=86400000

# Logging
logging.level.edu.dosw=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.security=DEBUG

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.enabled=true

# Configuración Redis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.enabled=true

# Logging para Redis
logging.level.org.springframework.data.redis=DEBUG